/**
 * @file		log_widget.h
 * @brief		Log message display widget module (header file).
 * @details		Contains type definitions, structures and functions for the log message display module.
 * @author		Arthur Markaryan
 * @date		01.05.2026
 * @version		1.0
 * @license		LGPL v3.0
 * @copyright	Arthur Markaryan
 *
 * @par ChangeLog:
 * 01.05.2026	v1.0	Base creation
 *
 * @see			LogWidget
 * @see			Message_TypeDef_t
 * @see			Message_Icon_e
 * @see			Message_Type_e
 * @see			Message_Timestamp_e
 */

#ifndef _LOG_WIDGET_H_
#define _LOG_WIDGET_H_

#include <QWidget>
#include <QDateTime>

/**
 * @defgroup	log_widget_icons Log Message Icons
 * @brief		Unicode icon symbols for log messages
 * @{
 */

#define ICON_NONE		""		//!< No icon for log message
#define ICON_SUCCESS	"✅ "	//!< Success/checkmark icon for successful operations
#define ICON_INFO		"ℹ️ "	//!< Information icon for informational messages
#define ICON_WARNING	"⚠️ "	//!< Warning icon for cautionary messages
#define ICON_ERROR		"❌ "	//!< Error icon for failure/error messages

/** @} */ // end of log_widget_icons group

/**
 * @defgroup	log_widget_enums Log Message Enumerations
 * @brief		Enumeration types for message configuration
 * @{
 */

/**
 * @brief		Message icon type enumeration
 * @details		Defines which icon to display with the log message.
 *				These values can be combined with appropriate message types.
 */
typedef enum {
    MESSAGE_ICON_NONE		= 0x00,		//!< No icon (0x00)
    MESSAGE_ICON_SUCCESS	= 0x01,		//!< Success/checkmark icon (bit 0)
    MESSAGE_ICON_INFO		= 0x04,		//!< Information icon (bit 2)
    MESSAGE_ICON_WARNING	= 0x08,		//!< Warning icon (bit 3)
    MESSAGE_ICON_ERROR		= 0x10,		//!< Error icon (bit 4)
} Message_Icon_e;

/**
 * @brief		Message type enumeration
 * @details		Defines the severity/category of the log message.
 *				Used for filtering and formatting purposes.
 */
typedef enum {
    MESSAGE_TYPE_NONE		= 0x00,		//!< No specific type (0x00)
    MESSAGE_TYPE_SUCCESS	= 0x01,		//!< Success message type (bit 0)
    MESSAGE_TYPE_INFO		= 0x04,		//!< Informational message type (bit 2)
    MESSAGE_TYPE_WARNING	= 0x08,		//!< Warning message type (bit 3)
    MESSAGE_TYPE_ERROR		= 0x10,		//!< Error message type (bit 4)
} Message_Type_e;

/**
 * @brief		Timestamp display format enumeration
 * @details		Defines what timestamp information to show with the log message.
 *				Multiple flags can be combined using bitwise OR.
 */
typedef enum {
    MESSAGE_TIMESTAMP_NONE			= 0x00,		//!< No timestamp (0x00)
    MESSAGE_TIMESTAMP_DATE			= 0x01,		//!< Show date only (YYYY-MM-DD) - bit 0
    MESSAGE_TIMESTAMP_TIME			= 0x02,		//!< Show time only (HH:MM:SS) - bit 1
    MESSAGE_TIMESTAMP_DATE_TIME		= 0x04,		//!< Show both date and time (bit 2)
} Message_Timestamp_e;

/** @} */ // end of log_widget_enums group

/**
 * @brief		Log message data structure
 * @details		Contains all necessary information for a single log message:
 *				- Icon type for visual representation
 *				- Message type for categorization
 *				- Timestamp format configuration
 *				- Actual message text content
 * @note		This structure is used as input for LogWidget::printMessage()
 * @see			LogWidget::printMessage()
 */
typedef struct {
    Message_Icon_e icon;		//!< Icon type to display (see Message_Icon_e)
    Message_Type_e type;		//!< Message category/severity (see Message_Type_e)
    Message_Timestamp_e timestamp;	//!< Timestamp format (see Message_Timestamp_e)
    QString text;			//!< Actual message content to display
} Message_TypeDef_t;

namespace Ui {
class LogWidget;
}

/**
 * @class		LogWidget
 * @brief		Custom widget for displaying log/service messages
 * @details		Provides a visual widget for displaying formatted log messages
 *				with support for icons, types, and timestamps.
 * @extends		QWidget
 */
class LogWidget : public QWidget
{
    Q_OBJECT

public:
    /**
     * @brief		Constructor for LogWidget
     * @param[in]	parent	Parent widget pointer (default: nullptr)
     * @details		Creates a new LogWidget instance and initializes the UI
     */
    explicit LogWidget(QWidget *parent = nullptr);

    /**
     * @brief		Destructor for LogWidget
     * @details		Cleans up UI resources
     */
    ~LogWidget();

public slots:
    /**
     * @brief		Print/displays a formatted log message
     * @param[in]	data	Reference to Message_TypeDef_t structure containing message data
     * @details		Formats and displays the message according to the specified
     *				icon, type and timestamp settings
     * @see			Message_TypeDef_t
     */
    void printMessage(const Message_TypeDef_t &data);

private:
    Ui::LogWidget *ui;	//!< User interface pointer for the log widget (auto-generated by Qt)
};

#endif // _LOG_WIDGET_H_
