/**
 * @file		log_widget.cpp
 * @brief		Log message display widget module (source file).
 * @details		Contains the implementation of the log message display module.
 * @author		Arthur Markaryan
 * @date		01.05.2026
 * @version		1.0
 * @license		LGPL v3.0
 * @copyright	Arthur Markaryan
 *
 * @par ChangeLog:
 * 01.05.2026	v1.0	Base creation
 *
 * @see			LogWidget
 * @see			Message_TypeDef_t
 * @see			utils.h
 */

#include "utils.h"
#include "log_widget.h"
#include "ui_log_widget.h"

/**
 * @brief		Constructor for LogWidget
 * @param[in]	parent	Parent widget pointer (default: nullptr)
 * @details		Initializes the user interface for the log widget.
 *				Sets up the UI components generated by Qt Designer.
 */
LogWidget::LogWidget(QWidget *parent)
    : QWidget(parent)
    , ui(new Ui::LogWidget)
{
    ui->setupUi(this);
}

/**
 * @brief		Destructor for LogWidget
 * @details		Cleans up the user interface resources by deleting the UI object.
 */
LogWidget::~LogWidget()
{
    delete ui;
}

/**
 * @brief		Prints/displays a formatted log message
 * @param[in]	data	Reference to Message_TypeDef_t structure containing message data
 * @details		This method performs the following steps to display a formatted message:
 *				- Adds an icon prefix based on the message icon type
 *				- Adds a colored type label ([Success], [Info], etc.) based on message type
 *				- Adds a timestamp prefix based on the timestamp format setting
 *				- Appends the actual message text to the log text edit widget
 *
 * @note		The message is displayed with HTML formatting for colored text.
 * @note		The timestamp uses the system's current date and time.
 * @see			Message_Icon_e
 * @see			Message_Type_e
 * @see			Message_Timestamp_e
 */
void LogWidget::printMessage(const Message_TypeDef_t &data)
{
    QString newMessage = "";

    // Add icon prefix (Unicode emoji characters)
    switch(data.icon)
    {
    case MESSAGE_ICON_SUCCESS:
        newMessage += QString(ICON_SUCCESS);		// Add green checkmark emoji
        break;
    case MESSAGE_ICON_INFO:
        newMessage += QString(ICON_INFO);			// Add information symbol emoji
        break;
    case MESSAGE_ICON_WARNING:
        newMessage += QString(ICON_WARNING);		// Add warning triangle emoji
        break;
    case MESSAGE_ICON_ERROR:
        newMessage += QString(ICON_ERROR);			// Add red cross mark emoji
        break;
    default:
        // No icon added for MESSAGE_ICON_NONE or unknown values
        break;
    }

    // Add message type label (HTML colored text)
    switch(data.type)
    {
    case MESSAGE_TYPE_SUCCESS:
        // Green, bold text for success messages
        newMessage += QString("<span style='color:green; white-space: pre; font-weight: bold;'>[Success] </span>");
        break;
    case MESSAGE_TYPE_INFO:
        // Blue, bold text for informational messages
        newMessage += QString("<span style='color:blue; white-space: pre; font-weight: bold;'>[ Info  ] </span>");
        break;
    case MESSAGE_TYPE_WARNING:
        // Orange, bold text for warning messages
        newMessage += QString("<span style='color:orange; white-space: pre; font-weight: bold;'>[Warning] </span>");
        break;
    case MESSAGE_TYPE_ERROR:
        // Red, bold text for error messages
        newMessage += QString("<span style='color:red; white-space: pre; font-weight: bold;'>[ Error ] </span>");
        break;
    default:
        // No type label added for MESSAGE_TYPE_NONE or unknown values
        break;
    }

    // Get system current date and time for timestamp
    QDateTime currentDateTime = QDateTime::currentDateTime();

    // Add timestamp prefix based on configured format
    switch(data.timestamp)
    {
    case MESSAGE_TIMESTAMP_NONE:
        // No timestamp added
        break;
    case MESSAGE_TIMESTAMP_DATE:
        // Format: [2025.12.25]
        newMessage += currentDateTime.toString("[yyyy.MM.dd] ");
        break;
    case MESSAGE_TIMESTAMP_TIME:
        // Format: [14:30:25.123]
        newMessage += currentDateTime.toString("[hh:mm:ss.zzz] ");
        break;
    case MESSAGE_TIMESTAMP_DATE_TIME:
        // Format: [2025.12.25 14:30:25.123]
        newMessage += currentDateTime.toString("[yyyy.MM.dd hh:mm:ss.zzz] ");
        break;
    default:
        // No timestamp added for unknown values
        break;
    }

    // Append the actual message text and display
    newMessage += data.text;
    ui->te_Message->append(newMessage);
}
