/**
 * @file        mainwindow.cpp
 * @brief       Implementation of the main window class.
 * @details     This file contains the implementation of the MainWindow class
 *              which represents the main application window. The constructor
 *              initializes the user interface generated by Qt Designer.
 * @author      Arthur Markaryan
 * @date        01.05.2026
 * @version     1.0
 * @license     LGPL v3.0
 * @copyright   Copyright (c) 2026
 *
 * @par Dependencies:
 * - mainwindow.h
 * - ui_mainwindow.h (auto-generated by Qt UIC)
 *
 * @par ChangeLog:
 * 01.05.2026   v1.0    Arthur Markaryan - Initial implementation
 *
 * @see         MainWindow::MainWindow()
 * @see         MainWindow::~MainWindow()
 */

#include "utils.h"
#include "log_widget.h"

#include "mainwindow.h"
#include "./ui_mainwindow.h"

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);
}

MainWindow::~MainWindow()
{
    delete ui;
}
