/**
 * @file		mainwindow.cpp
 * @brief		Implementation of the main window class.
 * @details		This file contains the implementation of the MainWindow class
 *				which represents the main application window. The constructor
 *				initializes the user interface generated by Qt Designer.
 * @author		Arthur Markaryan
 * @date		01.05.2026
 * @version		1.0.1
 * @license		LGPL v3.0
 * @copyright	Copyright (c) 2026
 *
 * @par Dependencies:
 * - mainwindow.h
 * - ui_mainwindow.h (auto-generated by Qt UIC)
 *
 * @par ChangeLog:
 * 01.05.2026	v1.0.1	Arthur Markaryan - Add base functional and log widget
 * 01.05.2026	v1.0	Arthur Markaryan - Initial implementation
 *
 * @see			MainWindow::MainWindow()
 * @see			MainWindow::~MainWindow()
 * @see			MainWindow::updateWindowTitle()
 */

#include "mainwindow.h"
#include "./ui_mainwindow.h"
#include <qtimer.h>

/**
 * @brief		Constructor for MainWindow
 * @param[in]	parent	Parent widget pointer (default: nullptr)
 * @details		Performs the following initialization steps:
 *				- Sets up the UI from Qt Designer
 *				- Resizes the main window to 800x600 pixels
 *				- Builds the application title with version numbers
 *				- Connects the logMessage signal to LogWidget::printMessage()
 *				- Creates and starts a 1-second timer for title updates
 *				- Emits a welcome message to the log widget
 */
MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    // Initialize UI
    ui->setupUi(this);

    // Set main window size
    resize(800, 600);

    // Initialize the main window title
    Title = QString("uBak - Backup Tool v%1.%2.%3.%4")
                .arg(UBAK_VERSION_MAIN)
                .arg(UBAK_VERSION_SUB1)
                .arg(UBAK_VERSION_SUB2)
                .arg(UBAK_VERSION_RC);

    // Connect signals
    connect(this, &MainWindow::logMessage, ui->w_LogWidget, &LogWidget::printMessage);

    // Create timer (for periodic window title updates)
    timer = new QTimer(this);
    // Connect timer signal to slot
    connect(timer, &QTimer::timeout, this, &MainWindow::updateWindowTitle);
    // Start timer with 1000 ms interval (1 second)
    timer->start(1000);

    // Emit welcome message to log widget
    emit logMessage((Message_TypeDef_t){
                                         MESSAGE_ICON_INFO,
                                         MESSAGE_TYPE_INFO,
                                         MESSAGE_TIMESTAMP_DATE_TIME,
                                         tr("Welcome to %1!").arg(Title)});
}

/**
 * @brief		Destructor for MainWindow
 * @details		Cleans up the user interface resources by deleting the UI object.
 */
MainWindow::~MainWindow()
{
    delete ui;
}

/**
 * @brief		Updates the window title with current date and time
 * @details		This slot is called every second by the timer.
 *				It retrieves the current system date and time, formats them,
 *				and appends them to the base application title.
 *				Example format: "uBak - Backup Tool v1.0.1.0 - 01.05.2026 14:30:25"
 */
void MainWindow::updateWindowTitle()
{
    // Get current date and time
    QDateTime currentDateTime = QDateTime::currentDateTime();

    // Format time according to preferences
    QString timeString = currentDateTime.toString("hh:mm:ss");
    QString dateString = currentDateTime.toString("dd.MM.yyyy");

    // Build the window title string
    QString windowTitle = QString("%1 - %2 %3").arg(Title, dateString, timeString);

    // Set the window title
    setWindowTitle(windowTitle);
}
