/**
 * @file		mainwindow.h
 * @brief		Main window module (header file).
 * @details		Contains the definition of the MainWindow class for Qt GUI application.
 * @note		...
 * @author		Arthur Markaryan
 * @date		01.05.2026
 * @version		1.0.1
 * @license		LGPL v3.0
 * @copyright	Copyright (c) 2026
 *
 * @par ChangeLog:
 * 01.05.2026	v1.0.1	Arthur Markaryan - Add base functional and log widget
 * 01.05.2026	v1.0	Base creation
 *
 * @par ToDo: ...
 */

#ifndef _MAINWINDOW_H_
#define _MAINWINDOW_H_

#include <QMainWindow>
#include <QTimer>

#include "utils.h"
#include "log_widget.h"

//! uBak application version number definitions
#define UBAK_VERSION_MAIN	(0x01U)	/*!< [31:24] main version */
#define UBAK_VERSION_SUB1	(0x00U)	/*!< [23:16] sub1 version */
#define UBAK_VERSION_SUB2	(0x01U)	/*!< [15:8]  sub2 version */
#define UBAK_VERSION_RC		(0x00U)	/*!< [7:0]  release candidate */
#define UBAK_VERSION		((UBAK_VERSION_MAIN << 24) \
                            | (UBAK_VERSION_SUB1 << 16) \
                            | (UBAK_VERSION_SUB2 << 8)  \
                            | (UBAK_VERSION_RC))

QT_BEGIN_NAMESPACE
namespace Ui {
class MainWindow;
}
QT_END_NAMESPACE

/**
 * @class		MainWindow
 * @brief		Main application window class
 * @details		Represents the main window of the uBak backup tool application.
 *				Handles UI initialization, window title updates, and log message forwarding.
 * @extends		QMainWindow
 */
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    /**
     * @brief		Constructor for MainWindow
     * @param[in]	parent	Parent widget pointer (default: nullptr)
     * @details		Initializes the user interface, sets up window size and title,
     *				connects signals/slots, starts the title update timer,
     *				and emits a welcome log message.
     */
    MainWindow(QWidget *parent = nullptr);

    /**
     * @brief		Destructor for MainWindow
     * @details		Cleans up UI resources.
     */
    ~MainWindow();

private:
    Ui::MainWindow *ui;		//!< User interface pointer (auto-generated by Qt)

    // Decorative elements
    QString Title;			//!< Application title string
    QTimer *timer;			//!< Timer pointer for periodic window title updates

signals:
    /**
     * @brief		Signal for sending messages to the log widget
     * @param[in]	message	Reference to Message_TypeDef_t structure containing log message data
     * @details		This signal is emitted to forward log messages to the LogWidget.
     * @see			LogWidget::printMessage()
     */
    void logMessage(const Message_TypeDef_t &message);

private slots:
    /**
     * @brief		Slot for updating the time in the window title
     * @details		Updates the main window title with the current date and time.
     *				Called periodically by the timer every second.
     */
    void updateWindowTitle();
};

#endif // _MAINWINDOW_H_
